server:
   port: 8041
user:
   name: Kishor
   password: 27892789
   xyz:
      abc: merge
notification:
   email:
      from: kishor@gmail.com
      message: Hello World! Email from the top of the world
   text:
      from: 274982347982
      message: Hello World! Text from the top of the world
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/client_int
      username: root
      password: 123456789
   jpa:
      properties:
         hibernate:
            show_sql: false
            format_sql: false
      database-platform: org.hibernate.dialect.MySQLDialect